name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'master' 
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h'
      - '**.c'
      - '**CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h'
      - '**.c'
      - '**CMakeLists.txt'
      - '.github/workflows/build.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04]
        build-type: [Debug, Release]
        include:
          - os: windows-latest
            cmake-args: '-AWin32 -Thost=x86 -DGH_ACBUILD=TRUE  -DUSING_BOOST_NO_CONAN=TRUE -DUSING_OPENSSL_NO_CONAN=TRUE -DBoost_NO_BOOST_CMAKE=ON'
          - os: ubuntu-22.04
            cmake-args: '-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DGH_ACBUILD=TRUE'

    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Set env
      run: echo "REPO_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
      shell: bash
    
    - if: runner.os == 'Windows'
      name: Install boost
      run: |
          $Url = "https://archives.boost.io/release/1.73.0/source/boost_1_73_0.zip"
          Invoke-WebRequest -Uri $Url -OutFile "$env:TEMP\boost.zip"
          Expand-Archive -Path "$env:TEMP\boost.zip" -DestinationPath "C:\hostedtoolcache\windows\Boost"

    - if: runner.os == 'Windows'
      name: Set boost env
      run: echo "BOOST_ROOT=C:\\hostedtoolcache\windows\\Boost\boost_1_73_0" >> $GITHUB_ENV
      shell: bash

    - if: runner.os == 'Windows'
      name: Install openssl
      run: |
        vcpkg install openssl:x86-windows-static-md
        "OPENSSL_ROOT=$env:VCPKG_INSTALLATION_ROOT\installed\x86-windows-static-md" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
    - if: runner.os == 'Linux'
      name: Install gcc/g++-multilib
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib

    - name: Get python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'

    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        python -m pip install "conan<2"

    - name: Generate build files
      run: mkdir build && cd build && cmake .. ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DDCC_VERSION="${{ env.REPO_TAG }}" -DBOOST_ROOT=${{ env.BOOST_ROOT }} -DOPENSSL_ROOT=${{ env.OPENSSL_ROOT }}

    - if: runner.os == 'Windows'
      name: Build Windows
      run: cd build && cmake --build . --config ${{ matrix.build-type }}

    - if: runner.os == 'Linux'
      name: Build Linux
      run: cd build && cmake --build .
      

    - name: Zip artifact
      run: Compress-Archive ${{ runner.workspace }}/samp-discord-connector/build/artifact/* ${{ runner.workspace }}/samp-discord-connector/build/artifact/discord-connector-${{ env.REPO_TAG }}-${{ runner.os }}-${{ matrix.build-type }}.zip
      shell: pwsh
      
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: discord-connector-${{ env.REPO_TAG }}-${{ runner.os }}-${{ matrix.build-type }}
        path: ${{ runner.workspace }}/samp-discord-connector/build/artifact/discord-connector-${{ env.REPO_TAG }}-${{ runner.os }}-${{ matrix.build-type }}.zip
